# Site settings
title: Bretts Blog
email: contact@brettyukich.co.nz
description: > # this means to ignore newlines until "baseurl:"
  A blog about the various small projects I spend my time on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.brettyukich.co.nz" # the base hostname & protocol for your site
github_username:  brettanomyces

# Build settings
markdown: kramdown
